using System;
using System.Collections.Generic;

// Token: 0x02001198 RID: 4504
public static class EntitlementAddressablesMaps
{
	// Token: 0x04006A77 RID: 27255
	public static readonly StringSpanDictionary<EntitlementSetEnum> AddressablesStringMap = new StringSpanDictionary<EntitlementSetEnum>
	{
		{
			"DLC/MarauderCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.MarauderCosmetic
		},
		{
			"DLC/HoarderCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.HoarderCosmetic
		},
		{
			"DLC/DesertCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.DesertCosmetic
		},
		{
			"DLC/PirateCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.PirateCosmetic
		},
		{
			"DLC/HellreaverCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.HellreaverCosmetic
		},
		{
			"DLC/ButcherCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.ButcherCosmetic
		},
		{
			"DLC/ClassicSurvivorCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.ClassicSurvivorCosmetic
		},
		{
			"DLC/WinterCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.WinterCosmetic
		},
		{
			"DLC/WorkingStiffCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.WorkingStiffCosmetic
		},
		{
			"DLC/CasualCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.CasualCosmetic
		},
		{
			"DLC/BeachCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.BeachCosmetic
		},
		{
			"DLC/MonsterMaskCosmetics".ToLowerInvariant(),
			EntitlementSetEnum.MonsterMaskCosmetics
		},
		{
			"DLC/StoryMaskCosmetics".ToLowerInvariant(),
			EntitlementSetEnum.StoryMaskCosmetics
		},
		{
			"DLC/ChristmasCosmetics".ToLowerInvariant(),
			EntitlementSetEnum.ChristmasCosmetics
		},
		{
			"DLC/CrimsonWarlordCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.CrimsonWarlordCosmetic
		},
		{
			"DLC/SamuraiCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.SamuraiCosmetic
		},
		{
			"DLC/HenpocalypseCosmetic".ToLowerInvariant(),
			EntitlementSetEnum.HenpocalypseCosmetic
		},
		{
			"TwitchDrops/PimpHatBlue".ToLowerInvariant(),
			EntitlementSetEnum.TwitchPimpHatBlueCosmetic
		},
		{
			"TwitchDrops/PimpHatPurple".ToLowerInvariant(),
			EntitlementSetEnum.TwitchPimpHatPurpleCosmetic
		},
		{
			"TwitchDrops/Watcher".ToLowerInvariant(),
			EntitlementSetEnum.TwitchWatcherCosmetic
		},
		{
			"TwitchDrops/CrackABookStoreGearOutfit".ToLowerInvariant(),
			EntitlementSetEnum.TwitchCrackABookStoreGearOutfitCosmetic
		},
		{
			"TwitchDrops/MoPowerStoreGearOutfit".ToLowerInvariant(),
			EntitlementSetEnum.TwitchMoPowerStoreGearOutfitCosmetic
		},
		{
			"TwitchDrops/PassNGasStoreGearOutfit".ToLowerInvariant(),
			EntitlementSetEnum.TwitchPassNGasStoreGearOutfitCosmetic
		},
		{
			"TwitchDrops/PopNPillsStoreGearOutfit".ToLowerInvariant(),
			EntitlementSetEnum.TwitchPopNPillsStoreGearOutfitCosmetic
		},
		{
			"TwitchDrops/SavageCountryStoreGearOutfit".ToLowerInvariant(),
			EntitlementSetEnum.TwitchSavageCountryStoreGearOutfitCosmetic
		},
		{
			"TwitchDrops/ShamwayStoreGearOutfit".ToLowerInvariant(),
			EntitlementSetEnum.TwitchShamwayStoreGearOutfitCosmetic
		},
		{
			"TwitchDrops/ShotgunMessiahStoreGearOutfit".ToLowerInvariant(),
			EntitlementSetEnum.TwitchShotgunMessiahStoreGearOutfitCosmetic
		},
		{
			"TwitchDrops/WorkingStiffsStoreGearOutfit".ToLowerInvariant(),
			EntitlementSetEnum.TwitchWorkingStiffsStoreGearOutfitCosmetic
		},
		{
			"TwitchDrops/CrackABookStoreGearHat".ToLowerInvariant(),
			EntitlementSetEnum.TwitchCrackABookStoreGearHatCosmetic
		},
		{
			"TwitchDrops/MoPowerStoreGearHat".ToLowerInvariant(),
			EntitlementSetEnum.TwitchMoPowerStoreGearHatCosmetic
		},
		{
			"TwitchDrops/PassNGasStoreGearHat".ToLowerInvariant(),
			EntitlementSetEnum.TwitchPassNGasStoreGearHatCosmetic
		},
		{
			"TwitchDrops/PopNPillsStoreGearHat".ToLowerInvariant(),
			EntitlementSetEnum.TwitchPopNPillsStoreGearHatCosmetic
		},
		{
			"TwitchDrops/SavageCountryStoreGearHat".ToLowerInvariant(),
			EntitlementSetEnum.TwitchSavageCountryStoreGearHatCosmetic
		},
		{
			"TwitchDrops/ShamwayStoreGearHat".ToLowerInvariant(),
			EntitlementSetEnum.TwitchShamwayStoreGearHatCosmetic
		},
		{
			"TwitchDrops/ShotgunMessiahStoreGearHat".ToLowerInvariant(),
			EntitlementSetEnum.TwitchShotgunMessiahStoreGearHatCosmetic
		},
		{
			"TwitchDrops/WorkingStiffsStoreGearHat".ToLowerInvariant(),
			EntitlementSetEnum.TwitchWorkingStiffsStoreGearHatCosmetic
		}
	};

	// Token: 0x04006A78 RID: 27256
	public static readonly Dictionary<object, EntitlementSetEnum> AddressablesKeyMap = new Dictionary<object, EntitlementSetEnum>();
}
