using System;
using System.Collections.Generic;
using System.ComponentModel;
using BhvrAnalyticsServices.Attributes;
using Newtonsoft.Json;

namespace Services.Analytics.Events
{
	// Token: 0x02001691 RID: 5777
	[EventTitle("Server Start")]
	public class ServerStartEventData : BaseEventData
	{
		// Token: 0x170015F9 RID: 5625
		// (get) Token: 0x0600B533 RID: 46387 RVA: 0x0043AB07 File Offset: 0x00438D07
		public override string EventType
		{
			get
			{
				return "server_start";
			}
		}

		// Token: 0x170015FA RID: 5626
		// (get) Token: 0x0600B534 RID: 46388 RVA: 0x0043AB0E File Offset: 0x00438D0E
		// (set) Token: 0x0600B535 RID: 46389 RVA: 0x0043AB16 File Offset: 0x00438D16
		[JsonProperty(PropertyName = "server_id")]
		[Description("The id of the server")]
		public string ServerId { get; set; }

		// Token: 0x170015FB RID: 5627
		// (get) Token: 0x0600B536 RID: 46390 RVA: 0x0043AB1F File Offset: 0x00438D1F
		// (set) Token: 0x0600B537 RID: 46391 RVA: 0x0043AB27 File Offset: 0x00438D27
		[Description("The save holding the world state")]
		[JsonProperty(PropertyName = "save_id")]
		public string SaveId { get; set; }

		// Token: 0x170015FC RID: 5628
		// (get) Token: 0x0600B538 RID: 46392 RVA: 0x0043AB30 File Offset: 0x00438D30
		// (set) Token: 0x0600B539 RID: 46393 RVA: 0x0043AB38 File Offset: 0x00438D38
		[JsonProperty(PropertyName = "server_start_ts")]
		[Description("Timestamp for when the server started")]
		[DateTimeFormat]
		public string ServerStartTimestamp { get; set; }

		// Token: 0x170015FD RID: 5629
		// (get) Token: 0x0600B53A RID: 46394 RVA: 0x0043AB41 File Offset: 0x00438D41
		// (set) Token: 0x0600B53B RID: 46395 RVA: 0x0043AB49 File Offset: 0x00438D49
		[JsonProperty(PropertyName = "server_type")]
		[Description("Type of server (Dedicated, Listen, Offline)")]
		public string ServerType { get; set; }

		// Token: 0x170015FE RID: 5630
		// (get) Token: 0x0600B53C RID: 46396 RVA: 0x0043AB52 File Offset: 0x00438D52
		// (set) Token: 0x0600B53D RID: 46397 RVA: 0x0043AB5A File Offset: 0x00438D5A
		[JsonProperty(PropertyName = "sandbox_seed")]
		[Description("Unique code generated by the sandbox settings")]
		public string SandboxSeed { get; set; }

		// Token: 0x170015FF RID: 5631
		// (get) Token: 0x0600B53E RID: 46398 RVA: 0x0043AB63 File Offset: 0x00438D63
		// (set) Token: 0x0600B53F RID: 46399 RVA: 0x0043AB6B File Offset: 0x00438D6B
		[JsonProperty(PropertyName = "sandbox_settings_delta")]
		public object SandboxSettingsDelta { get; set; }

		// Token: 0x17001600 RID: 5632
		// (get) Token: 0x0600B540 RID: 46400 RVA: 0x0043AB74 File Offset: 0x00438D74
		// (set) Token: 0x0600B541 RID: 46401 RVA: 0x0043AB7C File Offset: 0x00438D7C
		[JsonProperty(PropertyName = "world_name")]
		[Description("Unique id generated when creating the world")]
		public string WorldName { get; set; }

		// Token: 0x17001601 RID: 5633
		// (get) Token: 0x0600B542 RID: 46402 RVA: 0x0043AB85 File Offset: 0x00438D85
		// (set) Token: 0x0600B543 RID: 46403 RVA: 0x0043AB8D File Offset: 0x00438D8D
		[JsonProperty(PropertyName = "general_settings")]
		public Dictionary<string, object> GeneralSettings { get; set; }

		// Token: 0x17001602 RID: 5634
		// (get) Token: 0x0600B544 RID: 46404 RVA: 0x0043AB96 File Offset: 0x00438D96
		// (set) Token: 0x0600B545 RID: 46405 RVA: 0x0043AB9E File Offset: 0x00438D9E
		[JsonProperty(PropertyName = "server_mods")]
		[Description("List of mods with any information we can get")]
		public object ServerMods { get; set; }

		// Token: 0x17001603 RID: 5635
		// (get) Token: 0x0600B546 RID: 46406 RVA: 0x0043ABA7 File Offset: 0x00438DA7
		// (set) Token: 0x0600B547 RID: 46407 RVA: 0x0043ABAF File Offset: 0x00438DAF
		[JsonProperty(PropertyName = "total_mods")]
		public int TotalMods { get; set; }
	}
}
